<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1"/>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="keywords" content="Web Developer"/>
    <meta name="description" content="PHP/SQL"/>
    <title>PHP.TAXI</title>
    <link type="text/css" rel="StyleSheet" href="/src/css/common.css"/>
    <link type="text/css" rel="StyleSheet" href="/src/css/layout.css"/>
    <script type="text/javascript" src="/src/lib/jquery.js"></script><!--[jquery]-->
    <script type="text/javascript" src="/src/lib/angular.js"></script><!--[angular]-->
    <script type="text/javascript" src="/src/lib/angular-route.js"></script>
    <script type="text/javascript" src="/src/js/core.js"></script>
    <script type="text/javascript" src="/src/js/common.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/src/js/lib/html5.js"></script><![endif]-->
</head>
<body>
<header>

</header>
