<!DOCTYPE HTML>
<html>
<head>
    <title>PHP.TAXI</title>
    <!--[meta]-->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge, chrome=1"/>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="keywords" content="Web Developer"/>
    <meta name="description" content="PHP/SQL"/>
    <!--[favicon]-->
    <link rel="apple-touch-icon" href="/app_icon.png"><!-- 아이폰 전용 태그 -->
    <link rel="apple-touch-icon-precomposed" href="/app_icon.png"><!-- 안드로이드, 아이폰 모두 사용 가능한 태그 -->
    <!--[style]-->
    <link type="text/css" rel="StyleSheet" href="/src/css/common.css"/>
    <link type="text/css" rel="StyleSheet" href="/src/css/layout.css"/>
    <!--[jquery]-->
    <script type="text/javascript" src="/src/lib/jquery.js"></script>
    <!--[angular]-->
    <script type="text/javascript" src="/src/lib/angular.js"></script>
    <script type="text/javascript" src="/src/lib/angular-route.js"></script>
    <!--[custom]-->
    <script type="text/javascript" src="/src/js/core.js"></script>
    <script type="text/javascript" src="/src/js/common.js"></script>
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/src/js/lib/html5.js"></script><![endif]-->
</head>
<body>
<header></header>
