<?php

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!--meta-->
    <meta charset="UTF-8"/>
    <meta name="viewport"
          content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <!--library-->
    <script type="text/javascript" src="/src/lib/jquery.js"></script>
    <script type="text/javascript" src="/src/lib/angular.js"></script>
    <script type="text/javascript" src="/src/lib/angular-route.js"></script>
    <!--common-->
    <script type="text/javascript" src="/src/js/core.js"></script>
    <script type="text/javascript" src="/src/js/common.js"></script>
</head>
<body>
<header class="container">
    <nav>
        <a class="menu" href="#">메뉴</a>
    </nav>
</header>